OpenCBDC Transaction Processor: OpenCBDCJavaClient.cpp File Reference
OpenCBDCJavaClient.cpp File Reference
#include "atomizer_client.hpp"
#include "bech32/bech32.h"
#include "bech32/util/strencodings.h"
#include "client.hpp"
#include "crypto/sha256.h"
#include "hu_bme_mit_opencbdc_OpenCBDCJavaClient.h"
#include "twophase_client.hpp"
#include "uhs/transaction/messages.hpp"
#include "util/common/config.hpp"
#include "util/serialization/util.hpp"
#include <future>
#include <iostream>
#include <string>
Functions
auto mint_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto decode_address (const std::string &addr_str) -> std::optional< cbdc::hash_t >
std::string print_tx_result (const std::optional< cbdc::transaction::full_tx > &tx, const std::optional< cbdc::sentinel::response > &resp, const cbdc::hash_t &pubkey)
auto send_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto fan_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
void newaddress_command (cbdc::client &client)
auto importinput_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto confirmtx_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto call (std::vector< std::string > args) -> std::string
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_send (JNIEnv *env, jobject obj, jobjectArray arr)
Function Documentation
call()
auto call (std::vector< std::string > args) -> std::string
Definition at line 207 of file OpenCBDCJavaClient.cpp.
References confirmtx_command(), fan_command(), importinput_command(), cbdc::config::load_options(), mint_command(), newaddress_command(), cbdc::client::print_amount(), and send_command().
Referenced by Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_send().
confirmtx_command()
auto confirmtx_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 191 of file OpenCBDCJavaClient.cpp.
References cbdc::hash_from_hex(), cbdc::client::print_amount(), and cbdc::transaction::tx_id().
Referenced by call().
decode_address()
auto decode_address (const std::string & addr_str) -> std::optional<cbdc::hash_t>
Definition at line 37 of file OpenCBDCJavaClient.cpp.
References cbdc::client::public_key.
Referenced by fan_command(), and send_command().
fan_command()
auto fan_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 123 of file OpenCBDCJavaClient.cpp.
References decode_address(), and print_tx_result().
Referenced by call().
importinput_command()
auto importinput_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 173 of file OpenCBDCJavaClient.cpp.
References cbdc::buffer::from_hex().
Referenced by call().
Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_send()
JNIEXPORT jstring JNICALL Java_hu_bme_mit_opencbdc_OpenCBDCJavaClient_send (JNIEnv * env, jobject obj, jobjectArray arr)
Definition at line 297 of file OpenCBDCJavaClient.cpp.
References call(), and cbdc::transaction::tx_id().
mint_command()
auto mint_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 19 of file OpenCBDCJavaClient.cpp.
References cbdc::to_string(), and cbdc::transaction::tx_id().
Referenced by call().
newaddress_command()
void newaddress_command (cbdc::client & client)
Definition at line 153 of file OpenCBDCJavaClient.cpp.
References cbdc::client::new_address(), and cbdc::client::public_key.
Referenced by call().
print_tx_result()
std::string print_tx_result (const std::optional< cbdc::transaction::full_tx > & tx, const std::optional< cbdc::sentinel::response > & resp, const cbdc::hash_t & pubkey)
Definition at line 65 of file OpenCBDCJavaClient.cpp.
References cbdc::client::export_send_inputs(), cbdc::make_buffer(), cbdc::transaction::validation::to_string(), cbdc::to_string(), cbdc::sentinel::to_string(), and cbdc::transaction::tx_id().
Referenced by fan_command(), and send_command().
send_command()
auto send_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 96 of file OpenCBDCJavaClient.cpp.
References decode_address(), and print_tx_result().
Referenced by call().